### ISSUE TITLE
send change notifications to irc?

### ISSUE THREAD

**Issue by jrobeson** [beetbox/mediafile#4]
We do this for beets, but should we do it for mediafile?

**Comment by sampsyo** [comment]
Good idea! Done.

**Comment by jackwilsdon** [comment]
It looks like we're still missing the `notification` section from `.travis.yml`?

```YAML
notifications:
    irc:
        channels:
            - "irc.freenode.org#beets"
        use_notice: true
        skip_join: true
        on_success: change
        on_failure: always
```
